on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-by-author:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          direct_prompt: |
            Please provide a thorough review of this pull request.
            Pay extra attention to coding standards, security practices, and test coverage.
            Check for any missing, altered, or incorrect documentation in the docs/* directory.
